/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.18).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.jsr.pokemon.api;


import com.jsr.pokemon.model.Pokemon;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;



import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2021-02-21T00:02:36.778Z")

@Api(value = "pokemon", description = "the pokemon API")
@RequestMapping(value = "/v1")
public interface PokemonApi {

    @ApiOperation(value = "Find pokemon by Name", nickname = "getPokemonByName", notes = "Returns a single Pokemon", response = Pokemon.class, tags={ "pokemon", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Pokemon.class),
        @ApiResponse(code = 400, message = "Invalid Name supplied"),
        @ApiResponse(code = 404, message = "Pokemon not found") })
    @RequestMapping(value = "/pokemon/{pokemonName}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Pokemon> getPokemonByName(@ApiParam(value = "Name of Pokemon to return",required=true) @PathVariable("pokemonName") String pokemonName);


    @ApiOperation(value = "Find Pokemons", nickname = "getPokemonList", notes = "Returns a Pokemon List", response = Pokemon.class, responseContainer = "List", tags={ "pokemon", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Pokemon.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Pokemon not found") })
    @RequestMapping(value = "/pokemon",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Pokemon>> getPokemonList();

}
